#!/bin/sh /etc/rc.common
# ctrl+ON puts the calculator to sleep, ON wakes it up: see nspire-sleepd
START=12
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/nspire-sleepd
	procd_set_param respawn
	procd_close_instance
}
